### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by MikWCR** [Haizor/rotmg-dps-calculator#1]
Hello, the website is down. And has been for a few days now. Can i use this source to continue the project if you decide to drop it? Thank you

**Comment by Haizor** [comment]
People are free to do whatever they want with any of the projects I had my website.

**Comment by jones-josh** [comment]
Data files (e.g. https://www.haizor.net/rotmg/assets/production/xml/equip.xml) are similarly unaccessible and not present in the repository. Before I make a webscraper for RealmEye is there any way I can get these? Thanks.

**Comment by MikWCR** [comment]
> Data files (e.g. https://www.haizor.net/rotmg/assets/production/xml/equip.xml) are similarly unaccessible and not present in the repository. Before I make a webscraper for RealmEye is there any way I can get these? Thanks.

Have you got any of the data files? We can remake this dps calc if you'd want to.

**Comment by Haizor** [comment]
[Somebody else has already rehosted it, ](https://github.com/jy1263/rotmg-dps-calculator)but if you still want to remake it:

[https://github.com/AssetRipper/AssetRipper](https://github.com/AssetRipper/AssetRipper)
You can rip the assets from the game using this. Most Text Assets are XML files, and you only need the four main atlases (groundTiles, characters, and mapObjects) from the Texture2Ds. The only other major asset is the spritesheet.json, which is a text asset.

**Comment by amydevs** [comment]
Hi, just commenting to ask about the legality of hosting the XML files, etc. , I've made an automatic CI for it, but am unsure whether the Creative Commons License inside those files applies to all the files included in the original repository: [https://www.haizor.net/rotmg/assets/production/](https://www.haizor.net/rotmg/assets/production/xml/equip.xml)

**Comment by Haizor** [comment]
I mean technically it's probably not entirely legal to rehost the realm assets, but DECA doesn't seem to care if that's what you're asking.

**Comment by amydevs** [comment]
oh alright thanks!

**Comment by jones-josh** [comment]
@Haizor thanks for linking both the tool and the rehost, incredibly helpful + thanks for the work on this project overall.
